api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/DTO', '%kernel.project_dir%/src/ApiResource']
    use_symfony_listeners: true
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
