services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
    depends_on:
      - backend
    networks:
      - monea

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        TIMEZONE: Europe/Paris
    volumes:
      - ./back:/var/www/html
      - vendor-data:/var/www/html/vendor
    depends_on:
      - db
    networks:
      - monea
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./back:/var/www/html
    depends_on:
      - backend
    networks:
      - monea

  db:
    image: mysql:8.0
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./back/.env.local
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - monea

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    env_file:
      - ./back/.env.local
    depends_on:
      - db
    networks:
      - monea

volumes:
  db-data:
  vendor-data:

networks:
  monea:
