services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
    depends_on:
      - backend
    networks:
      - monea

  backend:
    build:
      context: ./back/.docker/php
      dockerfile: Dockerfile
    volumes:
      - ./back:/var/www/html
    depends_on:
      - db
    networks:
      - monea
  nginx:
    build:
      context: ./back/.docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./back:/var/www/symfony
    depends_on:
      - backend
    networks:
      - monea

  db:
    image: mysql:8.0
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - monea

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - monea

volumes:
  db-data:

networks:
  monea:
