<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250614134719 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE MON_BUDGET (BGT_ID INT AUTO_INCREMENT NOT NULL, BGT_AMOUNT DOUBLE PRECISION NOT NULL, BGT_MONTH_START DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CAT_ID INT NOT NULL, INDEX IDX_52A7F06F2E182825 (CAT_ID), PRIMARY KEY(BGT_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MON_CATEGORY (CAT_ID INT AUTO_INCREMENT NOT NULL, CAT_LABEL VARCHAR(50) NOT NULL, CAT_COLOR VARCHAR(8) NOT NULL, GRP_ID INT DEFAULT NULL, INDEX IDX_186C7E081DAB1036 (GRP_ID), PRIMARY KEY(CAT_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MON_EXPENSE (EXP_ID INT AUTO_INCREMENT NOT NULL, EXP_AMOUNT DOUBLE PRECISION NOT NULL, EXP_TITLE VARCHAR(255) NOT NULL, EXP_CREATED_AT DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', EXP_SPENT_AT DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', GRP_ID INT NOT NULL, CAT_ID INT NOT NULL, USR_ID INT NOT NULL, REC_ID INT DEFAULT NULL, INDEX IDX_CAF2C141DAB1036 (GRP_ID), INDEX IDX_CAF2C142E182825 (CAT_ID), INDEX IDX_CAF2C14C4DC529D (USR_ID), INDEX IDX_CAF2C14DEDC30FD (REC_ID), PRIMARY KEY(EXP_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MON_GROUPE (GRP_ID INT AUTO_INCREMENT NOT NULL, GRP_NAME VARCHAR(255) NOT NULL, GRP_CREATED_AT DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', GRP_TYPE VARCHAR(255) NOT NULL, GRP_PICTURE VARCHAR(255) NOT NULL, GRP_COLOR VARCHAR(255) NOT NULL, USR_ID INT NOT NULL, INDEX IDX_25EC8B35C4DC529D (USR_ID), PRIMARY KEY(GRP_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MON_MEMBER (MBR_ROLE VARCHAR(255) NOT NULL, MBR_ADD_ON DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', GRP_ID INT NOT NULL, USR_ID INT NOT NULL, INDEX IDX_51B1FD6C1DAB1036 (GRP_ID), INDEX IDX_51B1FD6CC4DC529D (USR_ID), PRIMARY KEY(GRP_ID, USR_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MON_RECURRING_EXPENSE (REC_ID INT AUTO_INCREMENT NOT NULL, REC_REPETITION_COUNT INT NOT NULL, REC_FREQUENCY_UNIT VARCHAR(20) NOT NULL, REC_END_DATE DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', PRIMARY KEY(REC_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MON_USER (USR_ID INT AUTO_INCREMENT NOT NULL, USR_USERNAME VARCHAR(50) NOT NULL, USR_NAME VARCHAR(50) NOT NULL, USR_LASTNAME VARCHAR(50) NOT NULL, USR_EMAIL VARCHAR(255) NOT NULL, USR_PASSWORD VARCHAR(255) NOT NULL, USR_ROLES JSON NOT NULL COMMENT '(DC2Type:json)', USR_CREATED_AT DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', USR_PICTURE VARCHAR(255), USR_RESET_TOKEN VARCHAR(255), UNIQUE INDEX UNIQ_70AADA227514CDD6 (USR_USERNAME), PRIMARY KEY(USR_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MON_SHARE_EXPENSE (USR_ID INT NOT NULL, EXP_ID INT NOT NULL, INDEX IDX_CF8CBBF3C4DC529D (USR_ID), INDEX IDX_CF8CBBF31AD3A99C (EXP_ID), PRIMARY KEY(USR_ID, EXP_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', available_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', delivered_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_BUDGET ADD CONSTRAINT FK_52A7F06F2E182825 FOREIGN KEY (CAT_ID) REFERENCES MON_CATEGORY (CAT_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_CATEGORY ADD CONSTRAINT FK_186C7E081DAB1036 FOREIGN KEY (GRP_ID) REFERENCES MON_GROUPE (GRP_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_EXPENSE ADD CONSTRAINT FK_CAF2C141DAB1036 FOREIGN KEY (GRP_ID) REFERENCES MON_GROUPE (GRP_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_EXPENSE ADD CONSTRAINT FK_CAF2C142E182825 FOREIGN KEY (CAT_ID) REFERENCES MON_CATEGORY (CAT_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_EXPENSE ADD CONSTRAINT FK_CAF2C14C4DC529D FOREIGN KEY (USR_ID) REFERENCES MON_USER (USR_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_EXPENSE ADD CONSTRAINT FK_CAF2C14DEDC30FD FOREIGN KEY (REC_ID) REFERENCES MON_RECURRING_EXPENSE (REC_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_GROUPE ADD CONSTRAINT FK_25EC8B35C4DC529D FOREIGN KEY (USR_ID) REFERENCES MON_USER (USR_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_MEMBER ADD CONSTRAINT FK_51B1FD6C1DAB1036 FOREIGN KEY (GRP_ID) REFERENCES MON_GROUPE (GRP_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_MEMBER ADD CONSTRAINT FK_51B1FD6CC4DC529D FOREIGN KEY (USR_ID) REFERENCES MON_USER (USR_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_SHARE_EXPENSE ADD CONSTRAINT FK_CF8CBBF3C4DC529D FOREIGN KEY (USR_ID) REFERENCES MON_USER (USR_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_SHARE_EXPENSE ADD CONSTRAINT FK_CF8CBBF31AD3A99C FOREIGN KEY (EXP_ID) REFERENCES MON_EXPENSE (EXP_ID)
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_BUDGET DROP FOREIGN KEY FK_52A7F06F2E182825
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_CATEGORY DROP FOREIGN KEY FK_186C7E081DAB1036
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_EXPENSE DROP FOREIGN KEY FK_CAF2C141DAB1036
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_EXPENSE DROP FOREIGN KEY FK_CAF2C142E182825
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_EXPENSE DROP FOREIGN KEY FK_CAF2C14C4DC529D
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_EXPENSE DROP FOREIGN KEY FK_CAF2C14DEDC30FD
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_GROUPE DROP FOREIGN KEY FK_25EC8B35C4DC529D
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_MEMBER DROP FOREIGN KEY FK_51B1FD6C1DAB1036
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_MEMBER DROP FOREIGN KEY FK_51B1FD6CC4DC529D
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_SHARE_EXPENSE DROP FOREIGN KEY FK_CF8CBBF3C4DC529D
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MON_SHARE_EXPENSE DROP FOREIGN KEY FK_CF8CBBF31AD3A99C
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MON_BUDGET
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MON_CATEGORY
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MON_EXPENSE
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MON_GROUPE
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MON_MEMBER
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MON_RECURRING_EXPENSE
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MON_USER
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MON_SHARE_EXPENSE
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE messenger_messages
        SQL);
    }
}
